<a href="https://colab.research.google.com/github/ashishgnsu/face_mask_detection/blob/main/numpyPart2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]

import time
c=[]
start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time() - start)

1.7462925910949707


In [ ]:
import numpy as np

a = np.arange(10000000)
b = np.arange(10000000, 20000000)

start = time.time()

c = a + b
print(time.time() - start)



0.37628769874572754


In [ ]:
#fancy indenxing
a = np.arange(24).reshape(6,4)

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[[0,3,4],[1,2,3]]

array([ 1, 14, 19])

In [ ]:
#boolean indexing

a = np.random.randint(1,100,24).reshape(6,4)
a

array([[95, 75, 96, 28],
       [ 9, 95, 81, 42],
       [69, 45, 97, 53],
       [46, 46, 91, 50],
       [76, 79, 31, 93],
       [85, 24, 56, 96]])

In [ ]:
#  find all the number greatervthan 50
#isko hum ek filter ki trh use krnege taki jha jha true sirf hum uska value get kr ske
a > 50

array([[ True,  True,  True, False],
       [False,  True,  True, False],
       [ True, False,  True,  True],
       [False, False,  True, False],
       [ True,  True, False,  True],
       [ True, False,  True,  True]])

In [ ]:
a[a > 50]

array([95, 75, 96, 95, 81, 69, 97, 53, 91, 76, 79, 93, 85, 56, 96])

In [ ]:
# find out all the even numbers
a[a % 2 == 0]

array([96, 28, 42, 46, 46, 50, 76, 24, 56, 96])

In [ ]:
#find all the values greater than 50 and even
a[(a > 50) & (a % 2 ==0)]

array([96, 76, 56, 96])

In [ ]:
# find all the number divisible by 7
a[a % 7 ==0]

array([28, 42, 91, 56])